### ISSUE TITLE
Could you please help me?

### ISSUE THREAD

**Issue by Hektor08** [linuslin0/ACST#120]
I've tried to use this tool to be able to continue my AC Origins game progress on my new account but it didn't work... I probably messed something up.
Could you please tell me if I should write my old account ID (with the saved game progress) as the encryption ID and my new account ID as the decryption ID or the other way around? 
Also, should I open all the saved files from both accounts, or only those which are on my old one?
Finally, after the conversion is complete, which files should I copy to where exactly?
I'm terribly sorry for my lack of IT knowledge. I know all these questions probably sound really obvious to you, but for someone who has only learnt 2 years IT back in high school (from which 1 was only IT history that started from the cave paintings xd) these things can be pretty hard to understand.

**Comment by linuslin0** [comment]
Your old account ID should be put into the Decryption ID field. And use your new account ID as Encryption ID.
You just need to load the saves from your old account since those would be the saves you want to convert and use on your new account.
After the conversion, copy those saves you just loaded (mostly likely still in the same file names for AC Origins). Files in acst_backup folder are the backup.

**Comment by Hektor08** [comment]
It's working. 
Thanks a lot man.
