### ISSUE TITLE
All my stats are different

### ISSUE THREAD

**Issue by camjorg** [linuslin0/ACST#160]
I uploaded a save that was 100 percent complete from Nexus mods. But now my Ubisoft account is reflecting all the wrong play time and stats. Is this common or did I something wrong? Suggestions for reversal?

**Comment by linuslin0** [comment]
Depending on different title, some stats are populated from the game save while others are not. AFAIK there is no way to modify/reset those stats other than reaching out to the official support.

**Comment by devashish-bhake** [comment]
can you share some screenshots as examples so that i can take a look?

**Comment by camjorg** [comment]
That would be helpful if there were before screenshots but there are not. Notice on the shot provided that the hours is 116. I only have played around 40. 
@devashish-bhake 
![Mirage1](https://github.com/user-attachments/assets/e7ae600d-44df-4482-99e7-ba06ed859569)

**Comment by devashish-bhake** [comment]
> That would be helpful if there were before screenshots but there are not. Notice on the shot provided that the hours is 116. I only have played around 40. 
> 
> @devashish-bhake 
> 
> ![Mirage1](https://github.com/user-attachments/assets/e7ae600d-44df-4482-99e7-ba06ed859569)
> 
> 

Ohhk i kinda understand what is happening. The thing is, during the process to set it up when we load it once in an offline fashion before loading up with the internet "on", the save file changes the stored data on the pc. Since, the save file has been played for 100+ hours it will load up those stats and sync it with the cloud, which is then reflecting on the account. I hope it clears out.

And no there is nothing that can be done for it.
